### PR TITLE
Fixes Issues #222 and #99

### LINKED ISSUE #99: touch events not working after v1.4.1
When I try to use the touch events with a version of processing.js after 1.4.1 I get the following error in the console: "Uncaught ReferenceError: eventHandlers is not defined" and the touch events are not working, when using 1.4.1 it works but i get another message in the console: "Uncaught InvalidStateError: Failed to execute 'dispatchEvent' on 'EventTarget': The event is already being dispatched.".
I used the example code from this page: http://www.bradchen.com/blog/2011/04/processing-js-touch-events
This problem occurred with chrome on android, safari on iOS and when using the touch screen emulator of chrome on windows to try it on the pc.
When using v1.4.1 it works, with v1.4.7 and after it doesn't and I get the first error message.

### LINKED ISSUE #222: Touch Input Broken
Sketches running on mobile/touchscreen devices don't respond to touch events.
Mouse functions don't get called at all, and experimenting with the undocumented touch events proved fruitless. Even a sketch as simple as this -

```
void setup() {
  size(300,300);
}

void draw() {
  if( mousePressed ) {
    ellipse(mouseX,mouseY,10,10);
  }
}
```
- doesn't work. Any idea what the issue here is?

Thanks,
Sam

EDIT: These sketches _do_ work in normal browsers on computers

### PR DESCRIPTION
**Pull request by frogg**
I've seen pull request #118 which tries to fix #99. However there was one bug remaining which is fixed with this pull request. This fixes #222 as well since the same scenario is described.

### CODE REVIEW

**Comment by frogg** [comment]
I'm not sure regarding the exported .js files. Should they be part of my pull request? Is there some kind of build server that creates those files automatically?

**Comment by GoToLoop** [comment]
File _"processing.js"_ is already auto-generated from folder "src/".

**Comment by frogg** [comment]
@GoToLoop thanks. I'm asking because this pull request indicates merge conflicts in these files. So I'm asking myself if it was correct to generate those files locally and add them to my commit or if they are generated by some kind of build server.

**Comment by GoToLoop** [comment]
You should remove them from your commit here. They're gonna be re-generated after all.

**Comment by frogg** [comment]
@GoToLoop ok, I've discarded my changes in those files, this resolved the merge conflicts.

**Comment by GoToLoop** [comment]
Now you'll have to w8 for the only gatekeeper here.  :P

File: src/Processing.js [hunk 1]
```diff
@@ -127,15 +127,13 @@
     // JavaScript event binding and releasing
     ////////////////////////////////////////////////////////////////////////////
 
-    var eventHandlers = [];
```
Comment (Pomax) [inline src/Processing.js]: Hm, is this change necessary? The variable scoping is already 1-to-1, with one `p` instance matched to a single `eventHandlers` in this code - keeping the eventHandlers list off of the instance itself prevents potential collisions with user code bindings, so I'd strongly recommend keeping this here, rather than adding it onto `p`.

From looking at the code, just having the `detachEventHandlersByType` update on line 173 *should* still do the trick.

Comment (frogg) [inline src/Processing.js]: You are right. I've fixed this in 2e86251

**Comment by Pomax** [comment]
looks good to me, in it goes. Thanks for the help!

**Comment by Pomax** [comment]
v1.6.5 pushed to npm
