### PR TITLE
Fix issue #271 - hue value -1 causes crash

### LINKED ISSUE #271: fill hue of -1 crashes app
`colorMode(HSB);
fill(-1, 250, 250);`
crashes with the error "Uncaught TypeError: Cannot read property '0' of undefined"

### PR DESCRIPTION
**Pull request by ojcm**
Hue should be in range 0-255. Processing behaviour when given a hue value below '0' appears to be to use '0'. To replicate that behaviour and fix this issue we should force the hue value to 0 when it is a negative value.

The specific error the user saw was caused by switching on '-1' (the value of `Math.floor(hue / 60)` when h is -1) in function `toRGB`. As there is no case for '-1', the function didn't return anything. The function `color` then sets `r = rgb[0];`, but rgb is undefined, hence the error "Cannot read property '0' of undefined". 
To provide better diagnostics in future I've added a default case to the switch, this includes a debugging statement indicating that this case is unexpected.

Unit test confirms that negative hue value is treated as '0'.

Fixes #271

### CODE REVIEW

**Comment by GoToLoop** [comment]
You're modifying the auto-generated file instead of its actual source:
https://GitHub.com/processing-js/processing-js/blob/master/src/Processing.js#L3031

Also `h  = h < 0? 0 : h;` can be replaced w/ `h = Math.max(0, h);`.  :P

**Comment by ojcm** [comment]
Right, I'll change that. Do you think that is worth documenting this in the contributing documentation (perhaps in a 'newbies' section :P)?

Any reason why `h = Math.max(0, h);` is preferable to `h = h < 0? 0 : h;`? I can see it's more readable but I'd expect the `?` method to be more efficient, plus it's consistent with the upper limit checking above?

**Comment by GoToLoop** [comment]
> Do you think that is worth documenting this in the contributing documentation?

I believe **color.toRGB(h, s, b)** and its siblings are internal undocumented functions.
AFAIK, none of the passed arguments are supposed to be negative for HSB's **colorMode()**.
And I feel Pjs library shouldn't actively check for such illegal parameters.
Unless the original Processing Java Mode's implementation checks for it as well.

> Any reason why `h = Math.max(0, h);` is preferable to `h = h < 0? 0 : h;`?

None. And I'm all for it for the best performance approach!  (^_^)

**Comment by ojcm** [comment]
Changes are now in Processing.js rather than processing.js. :)

For the documentation, I was referring to the fact that changes need to be in 'Processing.js' rather than 'processing.js'. This wasn't obvious to me, but I'm fairly new to Javascript dev so perhaps it will be obvious to others. ;)

File: src/Processing.js [hunk 1]
```diff
@@ -3029,6 +3029,9 @@
       s = (s > colorModeY) ? colorModeY : s;
       b = (b > colorModeZ) ? colorModeZ : b;
 
+      // Limit values smaller than range
+      b = (h < 0) ? 0 : h;
```
Comment (GoToLoop) [inline src/Processing.js]: _b_?! Shouldn't it been `h = h>=0? h : 0;` instead?

Comment (GoToLoop) [inline src/Processing.js]: Oh, you've already corrected it while I was typing it.  :P

**Comment by Pomax** [comment]
@ojcm it's implicit in the "Once the browser reference tests start, your processing.js and processing.min.js have been successfully built" bit, which tell you that these are not files you edit manually, but that can certainly be made more explicit.

**Comment by Pomax** [comment]
v1.6.6 has been published to npm with your changes merged in.

**Comment by GoToLoop** [comment]
Still think this merge is very incoherent. B/c the other parameters _s_ & _b_ can also receive negative arguments for the same reason as _h_.

It's a domino effect: If we check for illegal value ranges for 1 parameter, by logic, we need to do the same for all the rest as well!

**Comment by ojcm** [comment]
It isn't quite that simple: a negative h value causes a JavaScript error, whereas negative s or b doesn't. Negative s and b produces a questionable output, but if a user provides bad input they should expect bad output. So there's less motivation to limit s and b.

Having said that, I think you're right and I should have limited s and b too. Mainly because without limiting them the behaviour is different to Processing.
For example h=100, s=-200, b=100 is gray in Processing but pink in Processing.js. If we limit s to >=0 then we'd have gray too.

**Comment by Pomax** [comment]
that logic doesn't hold though. There is no reason whatsoever to add safety checks around all parameters just because it was added to one. If one of them can cause a crash and the others can't, then fixing just the crash is perfectly fine without any need for additional work until there is an actual use case in which normal code causes erroneous behaviour.

Also note that there is zero requirement for one PR to cover multiple failures. If s<0 or b<0 is something Processing allows, and the reference docs don't say anything about "these values must be positive numbers" or some such, then filing multiple PRs to successively get to parity is perfectly acceptable.

After all, just because one PR lands doesn't mean no further fixes will ever be accepted for that codepath. And if they're subtly different issues, for instance `h` causing a crash, whereas `s`/`b` are merely not on par, then those should be two separate issues and working on them in two different PRs is certainly preferred.
